# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: demo_pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: